/*
 * Copyright (c) 2007-2018 Holger de Carne and contributors, All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.carne.filescanner.engine;

import java.io.IOException;
import java.io.InputStream;

/**
 * Interface used for exporting a file scanner result.
 */
public interface FileScannerResultExporter {

	/**
	 * The possible mime types for exporting.
	 */
	enum Type {

		APPLICATION_BINARY("application/binary");

		private final String mimeType;

		private Type(String mimeType) {
			this.mimeType = mimeType;
		}

		/**
		 * Gets this {@linkplain Type}'s mime type.
		 *
		 * @return this {@linkplain Type}'s mime type.
		 */
		public String mimeType() {
			return this.mimeType;
		}

	}

	/**
	 * Gets the name of this {@linkplain FileScannerResultExporter}.
	 *
	 * @return the name of this {@linkplain FileScannerResultExporter}.
	 */
	String name();

	/**
	 * Gets the mime type generated by this exporter.
	 *
	 * @return the mime type generated by this exporter.
	 */
	Type type();

	/**
	 * Gets the default file name to use for a file export.
	 *
	 * @param result the {@linkplain FileScannerResult} instance to export.
	 * @return the default file name to use for a file export.
	 */
	String defaultStreamName(FileScannerResult result);

	/**
	 * Gets the export data {@linkplain InputStream}.
	 *
	 * @param result the {@linkplain FileScannerResult} instance to export.
	 * @return the export data {@linkplain InputStream}.
	 * @throws IOException if an I/O error occurs.
	 */
	InputStream stream(FileScannerResult result) throws IOException;

}
