/*
 * Copyright (c) 2007-2018 Holger de Carne and contributors, All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.carne.filescanner.engine;

import java.io.IOException;

import de.carne.filescanner.engine.transfer.ExportTarget;

/**
 * Interface used for exporting a file scanner result.
 */
public interface FileScannerResultExporter {

	/**
	 * The possible data types for exporting.
	 */
	enum Type {

		APPLICATION_OCTET_STREAM("application/octet-stream");

		private final String mimeType;

		private Type(String mimeType) {
			this.mimeType = mimeType;
		}

		/**
		 * Gets the MIME type corresponding to this export data {@linkplain Type}.
		 *
		 * @return the MIME type corresponding to this export data {@linkplain Type}.
		 */
		public String mimeType() {
			return this.mimeType;
		}

	}

	/**
	 * Gets the name of this {@linkplain FileScannerResultExporter}.
	 *
	 * @return the name of this {@linkplain FileScannerResultExporter}.
	 */
	String name();

	/**
	 * Gets the data type generated by this exporter.
	 *
	 * @return the data type generated by this exporter.
	 */
	Type type();

	/**
	 * Gets the default file name to use for a file export.
	 *
	 * @param result the {@linkplain FileScannerResult} instance to export.
	 * @return the default file name to use for a file export.
	 */
	String defaultFileName(FileScannerResult result);

	/**
	 * Performs the data export.
	 *
	 * @param result the {@linkplain FileScannerResult} instance to export.
	 * @param target the {@linkplain ExportTarget} to export to.
	 * @throws IOException if an I/O error occurs.
	 */
	void export(FileScannerResult result, ExportTarget target) throws IOException;

}
