/*
 * Copyright (c) 2007-2019 Holger de Carne and contributors, All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.carne.filescanner.engine.transfer;

import java.io.Closeable;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

import de.carne.boot.check.Check;
import de.carne.filescanner.engine.FileScannerResult;

/**
 * Class used to output file scanner results in a generic manner to different kind of outputs.
 */
public final class RenderOutput implements Closeable {

	private final Renderer renderer;
	private final long limit;
	private long emitted = 0;
	private final Set<RenderOption> options = new HashSet<>();
	private boolean prepared = false;
	private RenderStyle currentStyle = RenderStyle.NORMAL;

	/**
	 * Constructs a new {@linkplain RenderOutput} instance.
	 *
	 * @param renderer the {@linkplain Renderer} to use for output generation.
	 */
	public RenderOutput(Renderer renderer) {
		this(renderer, -1);
	}

	/**
	 * Constructs a new {@linkplain RenderOutput} instance.
	 *
	 * @param renderer the {@linkplain Renderer} to use for output generation.
	 * @param limit the output limit to set.
	 */
	public RenderOutput(Renderer renderer, long limit) {
		this.renderer = renderer;
		this.limit = limit;
	}

	/**
	 * Convenience function for rendering the given {@linkplain FileScannerResult} to the given {@linkplain Renderer}.
	 *
	 * @param result the {@linkplain FileScannerResult} to render.
	 * @param renderer the {@linkplain Renderer} to use for output generation.
	 * @throws IOException if an I/O error occurs.
	 */
	public static void render(FileScannerResult result, Renderer renderer) throws IOException {
		try (RenderOutput out = new RenderOutput(renderer)) {
			result.render(out);
		}
	}

	/**
	 * Convenience function for rendering the given {@linkplain FileScannerResult} to the given {@linkplain Renderer}.
	 *
	 * @param result the {@linkplain FileScannerResult} to render.
	 * @param renderer the {@linkplain Renderer} to use for output generation.
	 * @param limit the output limit to set.
	 * @throws IOException if an I/O error occurs.
	 */
	public static void render(FileScannerResult result, Renderer renderer, long limit) throws IOException {
		try (RenderOutput out = new RenderOutput(renderer, limit)) {
			result.render(out);
		}
	}

	/**
	 * Checks whether no output has yet been generated by this instance.
	 *
	 * @return {@code true} if no output has yet been generated by this instance.
	 */
	public boolean isEmpty() {
		return !this.prepared;
	}

	/**
	 * Checks whether a set output limit has been reached.
	 *
	 * @return {@code true} if a set output limit has been reached.
	 */
	public boolean isLimitReached() {
		return this.limit >= 0 && this.emitted >= this.limit;
	}

	/**
	 * Enables the given {@linkplain RenderOption}.
	 * <p>
	 * Render options can only be changed before the first output is generated.
	 *
	 * @param option the {@linkplain RenderOption} to enable.
	 * @return the updated {@linkplain RenderOutput} for chaining.
	 */
	public RenderOutput enableOption(RenderOption option) {
		Check.assertTrue(!this.prepared);
		this.options.add(option);
		return this;
	}

	/**
	 * Disables the given {@linkplain RenderOption}.
	 * <p>
	 * Render options can only be changed before the first output is generated.
	 *
	 * @param option the {@linkplain RenderOption} to disable.
	 * @return the updated {@linkplain RenderOutput} for chaining.
	 */
	public RenderOutput disableOption(RenderOption option) {
		Check.assertTrue(!this.prepared);
		this.options.remove(option);
		return this;
	}

	/**
	 * Sets the {@linkplain RenderStyle} for subsequent write calls.
	 *
	 * @param style the {@linkplain RenderStyle} to set.
	 * @return the updated {@linkplain RenderOutput} for chaining.
	 */
	public RenderOutput setStyle(RenderStyle style) {
		this.currentStyle = style;
		return this;
	}

	/**
	 * Writes simple text to the output using the currently selected {@linkplain RenderStyle}.
	 *
	 * @param text the text to write.
	 * @return the updated {@linkplain RenderOutput} for chaining.
	 * @throws IOException if an I/O error occurs.
	 */
	public RenderOutput write(String text) throws IOException {
		prepareIfNeeded();
		this.emitted += this.renderer.emitText(this.currentStyle, text, false);
		return this;
	}

	/**
	 * Writes simple text as well as a line break to the output using the currently selected {@linkplain RenderStyle}.
	 *
	 * @param text the text to write.
	 * @return the updated {@linkplain RenderOutput} for chaining.
	 * @throws IOException if an I/O error occurs.
	 */
	public RenderOutput writeln(String text) throws IOException {
		prepareIfNeeded();
		this.emitted += this.renderer.emitText(this.currentStyle, text, true);
		return this;
	}

	/**
	 * Writes media data to the output using the currently selected {@linkplain RenderStyle}.
	 *
	 * @param source the media data to write.
	 * @return the updated {@linkplain RenderOutput} for chaining.
	 * @throws IOException if an I/O error occurs.
	 */
	public RenderOutput write(TransferSource source) throws IOException {
		prepareIfNeeded();
		this.emitted += this.renderer.emitMediaData(this.currentStyle, source, false);
		return this;
	}

	/**
	 * Writes media data as well as a line break to the output using the currently selected {@linkplain RenderStyle}.
	 *
	 * @param source the media data to write.
	 * @return the updated {@linkplain RenderOutput} for chaining.
	 * @throws IOException if an I/O error occurs.
	 */
	public RenderOutput writeln(TransferSource source) throws IOException {
		prepareIfNeeded();
		this.emitted += this.renderer.emitMediaData(this.currentStyle, source, true);
		return this;
	}

	/**
	 * Writes a line break to the output.
	 *
	 * @return the updated {@linkplain RenderOutput} for chaining.
	 * @throws IOException if an I/O error occurs.
	 */
	public RenderOutput writeln() throws IOException {
		prepareIfNeeded();
		this.emitted += this.renderer.emitText(this.currentStyle, "", true);
		return this;
	}

	@Override
	public void close() throws IOException {
		if (this.prepared) {
			this.renderer.emitEpilouge();
		}
		this.renderer.close();
	}

	private void prepareIfNeeded() throws IOException {
		if (!this.prepared) {
			this.renderer.emitPrologue(this.options);
			this.prepared = true;
		}
	}

}
